### ISSUE TITLE
problem with serial number

### ISSUE THREAD

**Issue by waleedaan** [CreativeMagicPanels/MagicTouch#2]
Dear All

i can't enter the purchased code through the magic panel
i get  Connection Error msg after it's open
<img width="315" alt=
<img width="388" alt="Screen Shot 2022-07-09 at 5 26 35 AM" src="https://user-images.githubusercontent.com/106822745/178088403-ce0a5910-97f6-4e4a-b3de-9fc39b3eb5a6.png">
"Screen Shot 2022-07-09 at 5 26 54 AM" src="https://user-images.githubusercontent.com/106822745/178088384-31271537-c2fc-4d59-829f-a719f9f2e4a6.png">
<img width="585" alt="Screen Shot 2022-07-09 at 5 33 18 AM" src="https://user-images.githubusercontent.com/106822745/178088466-1e5a0fac-b572-4b4a-b1ce-2875e1a255ab.png">

all the tine i need t
<img width="315" alt="Screen Shot 2022-07-09 at 5 26 54 AM" src="https://user-images.githubusercontent.com/106822745/178088420-c36a708f-956d-4d79-8688-27bd642112ac.png">
o enter the purchased code

please check the [attachment 

Note:  i used the both Serial numbers. (the same problem) 
My Email :  alothman@gmail.com

**Comment by waleedaan** [comment]
also when i select any button i have to enter the serial number again and again

**Comment by CreativeMagicPanels** [comment]
Hi, thanks for reaching out.

We’re sorry you’re having troubles.

Could you please check you have the option “Allow extensions to connect to the internet” inside Preferences / plugins checked? 
 
Please send an email to support@creativemagicpanel.com specifying the email address you used during checkout and they will help.

Thanks!
